language: go

go:
  - 1.8rc3
  - tip
os:
  - linux
  - osx
services:
  - redis-server
  - memcached

matrix:
  # failure is not an option
  # allow_failures:
  #  - go: tip
  fast_finish: true

before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install memcached; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then /usr/local/opt/memcached/bin/memcached -l 127.0.0.1:11211 -d; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install redis; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew services start redis; fi

install:
  - go get -tags esiall -t ./...
  - go get github.com/golang/lint/golint
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/mholt/caddy/...
  - go get github.com/vdobler/ht/...

script:
  - diff <(echo -n) <(gofmt -s -d .)
  - ineffassign .
  - go vet ./...
  - go test -tags esiall -race -count=4 ./...
  - ./integration.sh

after_script:
  - golint ./...
  - go test -tags esiall -run=ðŸ¤ -bench=. -count=1 -benchmem ./...
