language: go

go:
  - 1.8rc1
  - tip
os:
  - linux
  - osx

matrix:
  # failure is not an option
  # allow_failures:
  #  - go: tip
  fast_finish: true

install:
  - go get -t ./...
  - go get github.com/golang/lint/golint
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/mholt/caddy/...
  - go get github.com/vdobler/ht/...
  - go install github.com/vdobler/ht/cmd/ht

script:
  - diff <(echo -n) <(gofmt -s -d .)
  - ineffassign .
  - go vet ./...
  - go test -race -count=4 ./...
  - $TRAVIS_BUILD_DIR/integration.sh

after_script:
  - golint ./...
  - go test -run=ðŸ¤ -bench=. -count=1 -benchmem ./...
